// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8imzxwrQjNUSuip-DhZjaH6Ky-492Hds',
    appId: '1:606258863452:web:1784650b5e3c0404257599',
    messagingSenderId: '606258863452',
    projectId: 'mynotes-ds-b6bfa',
    authDomain: 'mynotes-ds-b6bfa.firebaseapp.com',
    storageBucket: 'mynotes-ds-b6bfa.firebasestorage.app',
    measurementId: 'G-Z4QKNT98DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAneAfZr3Duhlev0KZWennif2wrKtIc_as',
    appId: '1:606258863452:android:b1b44216ed8d73cf257599',
    messagingSenderId: '606258863452',
    projectId: 'mynotes-ds-b6bfa',
    storageBucket: 'mynotes-ds-b6bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCftVzcGdA9VtbymHsbgXiNkWmUnrLni5U',
    appId: '1:606258863452:ios:ce8f27e0306a6d43257599',
    messagingSenderId: '606258863452',
    projectId: 'mynotes-ds-b6bfa',
    storageBucket: 'mynotes-ds-b6bfa.firebasestorage.app',
    iosBundleId: 'ds.sadds.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCftVzcGdA9VtbymHsbgXiNkWmUnrLni5U',
    appId: '1:606258863452:ios:ce8f27e0306a6d43257599',
    messagingSenderId: '606258863452',
    projectId: 'mynotes-ds-b6bfa',
    storageBucket: 'mynotes-ds-b6bfa.firebasestorage.app',
    iosBundleId: 'ds.sadds.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8imzxwrQjNUSuip-DhZjaH6Ky-492Hds',
    appId: '1:606258863452:web:21331da6ce95991c257599',
    messagingSenderId: '606258863452',
    projectId: 'mynotes-ds-b6bfa',
    authDomain: 'mynotes-ds-b6bfa.firebaseapp.com',
    storageBucket: 'mynotes-ds-b6bfa.firebasestorage.app',
    measurementId: 'G-KJMS9R1FG6',
  );
}
